name: Deploy to Remote IIS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install OpenSSH
      run: |
        Add-WindowsCapability -Online -Name OpenSSH.Client*

    - name: Stop Site and App Pool
      run: |
         powershell -Command "Start-Process ssh -ArgumentList @('-o','StrictHostKeyChecking=no','-o','UserKnownHostsFile=/dev/null','Administrator@192.168.1.159','-p','Welcome@123','C:\\Windows\\System32\\inetsrv\\appcmd.exe','stop','site','test.com')"

         powershell -Command "Start-Process ssh -ArgumentList @('-o','StrictHostKeyChecking=no','-o','UserKnownHostsFile=/dev/null','Administrator@192.168.1.159','-p','Welcome@123','C:\\Windows\\System32\\inetsrv\\appcmd.exe','stop','site','test.com')"



    - name: Transfer files to remote server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        $env:PATH += ";C:\Program Files\Git\usr\bin"  # Add Git's bin directory to PATH
        mkdir C:\Users\runner\.ssh  # Create SSH directory
        Set-Content -Path C:\Users\runner\.ssh\id_rsa -Value $env:SSH_PRIVATE_KEY  # Write SSH private key
        ssh-keyscan -H remote-server >> C:\Users\runner\.ssh\known_hosts  # Add remote server's host key
        scp -r -o StrictHostKeyChecking=no -o UserKnownHostsFile=C:\Users\runner\.ssh\known_hosts path\to\build\folder username@remote-server:/path/to/remote/directory

    - name: Start Site and App Pool
      run: |
        sshpass -p 'Welcome@123' ssh Administrator@192.168.1.159 "C:\\Windows\\System32\\inetsrv\\appcmd.exe stop site 'SiteName'"
        sshpass -p 'Welcome@123' ssh Administrator@192.168.1.159 "C:\\Windows\\System32\\inetsrv\\appcmd.exe stop site 'SiteName'"
