name: Dotnet-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.0
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --output ./build
    - name: Test
      run: dotnet test --no-build --verbosity normal
