name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  example_job:
    runs-on: windows-latest

    steps:
      - name: Echo Secret
        run: |
          $secretValue = $env:MY_SECRET
          Write-Host "My secret value is: $secretValue"
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
