name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  example_job:
    runs-on: windows-latest

    steps:
      - name: Echo Secret
        run: |
          echo "My secret value is: ${{ secrets.MY_SECRET }}"
        # Mask the secret to prevent it from being displayed in the logs
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
