name: Transfer Test File to Remote Server

on:
  push:
    branches:
      - main

jobs:
  transfer_file:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create test file
      run: |
        echo "This is a test file" > testfile.txt
        echo "Additional content" >> testfile.txt

    - name: Install PuTTY
      run: |
        mkdir -p "C:\tools"
        Invoke-WebRequest "https://the.earth.li/~sgtatham/putty/latest/w64/pscp.exe" -OutFile "C:\tools\pscp.exe"

    - name: Transfer test file with password
      run: |
        "C:\tools\pscp.exe" -pw Welcome@123 testfile.txt Administrator@192.168.1.159:C:\inetpub\wwwroot\test.com
