name: Transfer File to Remote Server

on:
  push:
    branches:
      - main

jobs:
  transfer_file:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create test file
      run: |
        mkdir C:\testfolder
        echo "This is a test file" > C:\testfolder\testfile.txt
        echo "Additional content" >> C:\testfolder\testfile.txt
      shell: cmd

    - name: Transfer file to remote server
      run: |
        $password = ConvertTo-SecureString "Welcome@123" -AsPlainText -Force
        $username = "Administrator"
        $cred = New-Object System.Management.Automation.PSCredential ($username, $password)
        $session = New-PSSession -ComputerName "192.168.1.59" -Credential $cred
        Copy-Item -Path "C:\testfolder\testfile.txt" -Destination "C:\inetpub\wwwroot\test.com" -ToSession $session
        Remove-PSSession $session
