name: Transfer File to Remote Server

on:
  push:
    branches:
      - main

jobs:
  transfer_file:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create test file
      run: |
        echo "This is a test file" > C:\testfolder\testfile.txt
        echo "Additional content" >> C:\testfolder\testfile.txt
      shell: cmd

    - name: Transfer file to remote server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
      run: |
        mkdir C:\Users\Administrator\.ssh  # Create SSH directory
        Set-Content -Path C:\Users\Administrator\.ssh\id_rsa -Value "${{ secrets.SSH_KEY }}"  # Write SSH private key
        scp -o StrictHostKeyChecking=no -i C:\Users\Administrator\.ssh\id_rsa C:\testfolder\testfile.txt Administrator@192.168.1.159:C:\inetpub\wwwroot\test.com
